export const US_STATES = [
  { value: 'alabama', label: 'Alabama', code: 'AL' },
  { value: 'alaska', label: 'Alaska', code: 'AK' },
  { value: 'arizona', label: 'Arizona', code: 'AZ' },
  { value: 'arkansas', label: 'Arkansas', code: 'AR' },
  { value: 'california', label: 'California', code: 'CA' },
  { value: 'colorado', label: 'Colorado', code: 'CO' },
  { value: 'connecticut', label: 'Connecticut', code: 'CT' },
  { value: 'delaware', label: 'Delaware', code: 'DE' },
  { value: 'florida', label: 'Florida', code: 'FL' },
  { value: 'georgia', label: 'Georgia', code: 'GA' },
  { value: 'hawaii', label: 'Hawaii', code: 'HI' },
  { value: 'idaho', label: 'Idaho', code: 'ID' },
  { value: 'illinois', label: 'Illinois', code: 'IL' },
  { value: 'indiana', label: 'Indiana', code: 'IN' },
  { value: 'iowa', label: 'Iowa', code: 'IA' },
  { value: 'kansas', label: 'Kansas', code: 'KS' },
  { value: 'kentucky', label: 'Kentucky', code: 'KY' },
  { value: 'louisiana', label: 'Louisiana', code: 'LA' },
  { value: 'maine', label: 'Maine', code: 'ME' },
  { value: 'maryland', label: 'Maryland', code: 'MD' },
  { value: 'massachusetts', label: 'Massachusetts', code: 'MA' },
  { value: 'michigan', label: 'Michigan', code: 'MI' },
  { value: 'minnesota', label: 'Minnesota', code: 'MN' },
  { value: 'mississippi', label: 'Mississippi', code: 'MS' },
  { value: 'missouri', label: 'Missouri', code: 'MO' },
  { value: 'montana', label: 'Montana', code: 'MT' },
  { value: 'nebraska', label: 'Nebraska', code: 'NE' },
  { value: 'nevada', label: 'Nevada', code: 'NV' },
  { value: 'new-hampshire', label: 'New Hampshire', code: 'NH' },
  { value: 'new-jersey', label: 'New Jersey', code: 'NJ' },
  { value: 'new-mexico', label: 'New Mexico', code: 'NM' },
  { value: 'new-york', label: 'New York', code: 'NY' },
  { value: 'north-carolina', label: 'North Carolina', code: 'NC' },
  { value: 'north-dakota', label: 'North Dakota', code: 'ND' },
  { value: 'ohio', label: 'Ohio', code: 'OH' },
  { value: 'oklahoma', label: 'Oklahoma', code: 'OK' },
  { value: 'oregon', label: 'Oregon', code: 'OR' },
  { value: 'pennsylvania', label: 'Pennsylvania', code: 'PA' },
  { value: 'rhode-island', label: 'Rhode Island', code: 'RI' },
  { value: 'south-carolina', label: 'South Carolina', code: 'SC' },
  { value: 'south-dakota', label: 'South Dakota', code: 'SD' },
  { value: 'tennessee', label: 'Tennessee', code: 'TN' },
  { value: 'texas', label: 'Texas', code: 'TX' },
  { value: 'utah', label: 'Utah', code: 'UT' },
  { value: 'vermont', label: 'Vermont', code: 'VT' },
  { value: 'virginia', label: 'Virginia', code: 'VA' },
  { value: 'washington', label: 'Washington', code: 'WA' },
  { value: 'west-virginia', label: 'West Virginia', code: 'WV' },
  { value: 'wisconsin', label: 'Wisconsin', code: 'WI' },
  { value: 'wyoming', label: 'Wyoming', code: 'WY' },
];

export const LEGAL_TEMPLATE = 'legal-document-v1';
export const FINANCE_TEMPLATE = 'finance-document-v1';
export const HR_TEMPLATE = 'hr-document-v1';
export const BUSINESS_TEMPLATE = 'business-document-v1';
export const COPY_TEMPLATE = 'copy-document-v1';
