import type { Metadata } from 'next';
import Link from 'next/link';
import { ALL_TOOLS } from '@aifreetools/tool-configs';

export const metadata: Metadata = {
  title: 'About AIFreeTools — Free AI Tools for US Businesses',
  description:
    'AIFreeTools provides free AI-powered tools for legal documents, HR forms, financial planning, and business operations. Built for US businesses and professionals.',
  alternates: { canonical: '/about' },
};

const STATS = [
  { label: 'Free AI Tools', value: `${ALL_TOOLS.length}+` },
  { label: 'US States Supported', value: '50' },
  { label: 'Documents Generated', value: '10,000+' },
  { label: 'Signup Required', value: 'None' },
];

const VALUES = [
  {
    icon: '🆓',
    title: 'Always Free',
    desc: 'Core tools are permanently free. No credit card, no trial limits, no hidden fees.',
  },
  {
    icon: '🇺🇸',
    title: 'Built for the US',
    desc: 'Every tool is tailored for US law, US tax code, and US business practices — state-specific where it matters.',
  },
  {
    icon: '⚡',
    title: 'Instant Results',
    desc: 'Generate professional documents and content in seconds, not hours. AI does the heavy lifting.',
  },
  {
    icon: '🔒',
    title: 'Privacy First',
    desc: "Your inputs are not stored or sold. We don't require an account, so there's nothing to compromise.",
  },
];

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <section className="mb-16 text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Free AI Tools for Every US Business
        </h1>
        <p className="text-xl text-gray-500 max-w-2xl mx-auto leading-relaxed">
          We believe professional-quality legal documents, HR forms, and business tools shouldn't
          cost hundreds of dollars. AIFreeTools makes AI-powered productivity accessible to
          everyone.
        </p>
      </section>

      <section className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-16">
        {STATS.map((stat) => (
          <div key={stat.label} className="text-center bg-blue-50 rounded-xl p-6">
            <div className="text-3xl font-bold text-blue-700 mb-1">{stat.value}</div>
            <div className="text-sm text-gray-600">{stat.label}</div>
          </div>
        ))}
      </section>

      <section className="mb-16">
        <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">Our Values</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {VALUES.map((v) => (
            <div key={v.title} className="border border-gray-200 rounded-xl p-6">
              <div className="text-3xl mb-3">{v.icon}</div>
              <h3 className="font-bold text-lg mb-2">{v.title}</h3>
              <p className="text-gray-600 text-sm">{v.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mb-16">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Important Disclaimer</h2>
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 text-sm text-amber-900 leading-relaxed">
          <p className="font-semibold mb-2">⚠️ AI-generated content is for informational purposes only.</p>
          <p>
            The documents and content generated by AIFreeTools are not a substitute for
            professional legal, financial, or HR advice. Laws vary by state and situation. Always
            consult a licensed attorney, CPA, or HR professional before relying on AI-generated
            documents for important business decisions.
          </p>
        </div>
      </section>

      <section className="text-center bg-gradient-to-br from-blue-600 to-blue-800 rounded-2xl p-10 text-white">
        <h2 className="text-2xl font-bold mb-3">Ready to Save Hours Every Week?</h2>
        <p className="text-blue-100 mb-6">
          Browse {ALL_TOOLS.length} free AI tools — no account required.
        </p>
        <Link
          href="/tools"
          className="inline-block bg-white text-blue-700 font-semibold px-8 py-3 rounded-lg hover:bg-blue-50 transition-colors"
        >
          Browse All Tools →
        </Link>
      </section>
    </div>
  );
}
