import type { ToolConfig } from '@aifreetools/shared-types';
import { US_STATES, HR_TEMPLATE, LEGAL_TEMPLATE } from '../constants';

const jobDescriptionGenerator: ToolConfig = {
  id: 'job-description-generator',
  slug: 'job-description-generator',
  name: 'Free Job Description Generator',
  shortName: 'Job Description Generator',
  category: 'hr-recruitment',
  description: 'Generate ATS-optimized job descriptions with inclusive language, skill requirements, and compelling company culture sections.',
  tagline: 'Write job descriptions that attract top talent.',
  icon: 'briefcase',
  sortOrder: 19,
  isFeatured: true,
  formSchema: {
    fields: [
      { id: 'jobTitle', type: 'text', label: 'Job Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'department', type: 'text', label: 'Department', required: false, validation: { maxLength: 100 } },
      { id: 'jobType', type: 'select', label: 'Job Type', required: true, defaultValue: 'full_time', options: [{ value: 'full_time', label: 'Full-Time' }, { value: 'part_time', label: 'Part-Time' }, { value: 'contract', label: 'Contract' }, { value: 'freelance', label: 'Freelance' }, { value: 'internship', label: 'Internship' }] },
      { id: 'workLocation', type: 'radio', label: 'Work Location', required: true, defaultValue: 'hybrid', options: [{ value: 'onsite', label: 'On-site' }, { value: 'remote', label: 'Remote' }, { value: 'hybrid', label: 'Hybrid' }] },
      { id: 'salaryMin', type: 'currency', label: 'Salary Min ($)', required: false },
      { id: 'salaryMax', type: 'currency', label: 'Salary Max ($)', required: false },
      { id: 'experienceLevel', type: 'select', label: 'Experience Level', required: true, options: [{ value: 'entry', label: 'Entry Level (0-2 yrs)' }, { value: 'mid', label: 'Mid Level (3-5 yrs)' }, { value: 'senior', label: 'Senior (5-10 yrs)' }, { value: 'lead', label: 'Lead/Principal (8+ yrs)' }, { value: 'executive', label: 'Executive/Director' }] },
      { id: 'responsibilities', type: 'textarea', label: 'Key Responsibilities', required: true, validation: { minLength: 20, maxLength: 2000 }, placeholder: 'List the main duties and responsibilities...' },
      { id: 'skills', type: 'textarea', label: 'Required Skills & Qualifications', required: true, validation: { minLength: 20, maxLength: 1000 }, placeholder: 'List required and preferred skills...' },
      { id: 'industryType', type: 'select', label: 'Industry', required: false, options: [{ value: 'technology', label: 'Technology' }, { value: 'healthcare', label: 'Healthcare' }, { value: 'finance', label: 'Finance' }, { value: 'marketing', label: 'Marketing' }, { value: 'sales', label: 'Sales' }, { value: 'hr', label: 'Human Resources' }, { value: 'legal', label: 'Legal' }, { value: 'education', label: 'Education' }, { value: 'other', label: 'Other' }] },
    ],
    groups: [
      { id: 'basics', title: 'Job Details', fieldIds: ['jobTitle', 'company', 'department', 'jobType', 'workLocation', 'industryType', 'experienceLevel'] },
      { id: 'compensation', title: 'Compensation', fieldIds: ['salaryMin', 'salaryMax'] },
      { id: 'requirements', title: 'Requirements', fieldIds: ['responsibilities', 'skills'] },
    ],
  },
  promptConfig: {
    version: '1.1.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an HR expert and talent acquisition specialist. Generate compelling, ATS-optimized job descriptions with inclusive language that attracts diverse, qualified candidates.' },
      { id: 'generate', role: 'user', template: `Generate an ATS-optimized job description:\n\nTitle: {{jobTitle}}\nCompany: {{company}}\nDepartment: {{department}}\nType: {{jobType}} | {{workLocation}}\nLevel: {{experienceLevel}}\nSalary: \$\{\{salaryMin}}-\$\{\{salaryMax}}\nIndustry: {{industryType}}\nResponsibilities: {{responsibilities}}\nSkills: {{skills}}\n\nInclude: compelling job summary (2-3 sentences), responsibilities section (5-8 bullets), qualifications (required + preferred), what we offer/benefits, equal opportunity statement. Use inclusive language. Optimize for ATS keywords. Format with clear sections.` },
    ],
    outputFormat: 'text',
    maxTokens: 2000,
    temperature: 0.4,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Job-Description-{{jobTitle}}', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Job Description Generator — ATS-Optimized | AIFreeTools',
    descriptionTemplate: 'Generate ATS-optimized job descriptions with inclusive language in seconds. Free AI-powered tool for HR professionals and hiring managers.',
    primaryKeyword: 'free job description generator',
    keywords: ['job description generator', 'job posting generator', 'ats optimized job description', 'job description template', 'hr job description tool'],
    faqCount: 7,
    generateStatePages: false,
    articleTopics: ['how to write a job description', 'ats optimization tips', 'inclusive language in job postings', 'job description best practices'],
    relatedTools: ['job-offer-letter-generator', 'interview-questions-generator', 'performance-review-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['indeed', 'linkedin-jobs', 'bamboohr', 'gusto'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const resignationLetterGenerator: ToolConfig = {
  id: 'resignation-letter-generator',
  slug: 'resignation-letter-generator',
  name: 'Free Resignation Letter Generator',
  shortName: 'Resignation Letter Generator',
  category: 'hr-recruitment',
  description: 'Generate a professional resignation letter for any situation — standard resignation, toxic workplace, burnout, or career change.',
  tagline: 'Leave on good terms with a professional resignation letter.',
  icon: 'log-out',
  sortOrder: 20,
  isFeatured: true,
  formSchema: {
    fields: [
      { id: 'employeeName', type: 'text', label: 'Your Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'employerName', type: 'text', label: 'Manager/Supervisor Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'position', type: 'text', label: 'Your Current Position', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'lastDay', type: 'date', label: 'Last Working Day', required: true },
      { id: 'noticePeriod', type: 'select', label: 'Notice Period', required: true, defaultValue: '2_weeks', options: [{ value: 'immediate', label: 'Immediate (no notice)' }, { value: '1_week', label: '1 Week' }, { value: '2_weeks', label: '2 Weeks' }, { value: '1_month', label: '1 Month' }, { value: '2_months', label: '2 Months' }] },
      { id: 'reason', type: 'select', label: 'Reason for Leaving', required: true, options: [{ value: 'new_opportunity', label: 'New Job Opportunity' }, { value: 'career_change', label: 'Career Change' }, { value: 'relocation', label: 'Relocation' }, { value: 'personal', label: 'Personal Reasons' }, { value: 'burnout', label: 'Burnout/Health' }, { value: 'retirement', label: 'Retirement' }, { value: 'prefer_not_say', label: 'Prefer Not to Say' }] },
      { id: 'tone', type: 'radio', label: 'Tone', required: true, defaultValue: 'professional_warm', options: [{ value: 'professional_warm', label: 'Professional & Warm' }, { value: 'formal', label: 'Formal & Neutral' }, { value: 'brief', label: 'Brief & Direct' }] },
      { id: 'offerTransition', type: 'toggle', label: 'Offer to help with transition?', defaultValue: true },
    ],
    groups: [
      { id: 'details', title: 'Details', fieldIds: ['employeeName', 'employerName', 'company', 'position', 'lastDay', 'noticePeriod'] },
      { id: 'content', title: 'Content', fieldIds: ['reason', 'tone', 'offerTransition'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an HR professional and career coach. Generate professional resignation letters that maintain positive relationships while clearly communicating the resignation.' },
      { id: 'generate', role: 'user', template: `Generate a {{tone}} resignation letter:\n\nFrom: {{employeeName}} ({{position}})\nTo: {{employerName}}, {{company}}\nLast Day: {{lastDay}}\nNotice: {{noticePeriod}}\nReason: {{reason}}\nTransition help: {{offerTransition}}\n\nWrite a professional letter that: states the resignation clearly, gives the final date, expresses appropriate gratitude (without being excessive), {{#if offerTransition}}offers to help with transition{{/if}}. Keep it concise — under 250 words. Do not mention the actual reason if it's negative.` },
    ],
    outputFormat: 'text',
    maxTokens: 800,
    temperature: 0.4,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Resignation-Letter', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Resignation Letter Generator — Professional Templates | AIFreeTools',
    descriptionTemplate: 'Generate a professional resignation letter for any situation. AI-powered, multiple tones available. Free PDF download. Leave on good terms.',
    primaryKeyword: 'free resignation letter generator',
    keywords: ['resignation letter generator', 'free resignation letter', 'how to resign professionally', 'resignation letter template', 'two weeks notice letter'],
    faqCount: 7,
    generateStatePages: false,
    articleTopics: ['how to write a resignation letter', 'two weeks notice best practices', 'quitting gracefully', 'resignation dos and donts'],
    relatedTools: ['termination-letter-generator', 'job-offer-letter-generator', 'reference-letter-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['linkedin', 'indeed', 'glassdoor'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
    leadGenCTA: 'Find your next opportunity. Search jobs on Indeed.',
  },
};

const referenceLetterGenerator: ToolConfig = {
  id: 'reference-letter-generator',
  slug: 'reference-letter-generator',
  name: 'Free Reference Letter Generator',
  shortName: 'Reference Letter Generator',
  category: 'hr-recruitment',
  description: 'Generate professional reference letters for employees, students, or colleagues with role-specific recommendations and achievement highlights.',
  tagline: 'Write a powerful reference letter in minutes.',
  icon: 'star',
  sortOrder: 21,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'writerName', type: 'text', label: 'Your Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'writerTitle', type: 'text', label: 'Your Title/Position', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'writerCompany', type: 'text', label: 'Your Company/Organization', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'candidateName', type: 'text', label: 'Candidate Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'referenceType', type: 'select', label: 'Reference Type', required: true, options: [{ value: 'employment', label: 'Employment' }, { value: 'academic', label: 'Academic' }, { value: 'character', label: 'Character' }, { value: 'professional', label: 'Professional/Industry' }] },
      { id: 'relationship', type: 'text', label: 'Your Relationship to Candidate', required: true, placeholder: 'e.g. Direct supervisor for 3 years', validation: { minLength: 5, maxLength: 200 } },
      { id: 'keyStrengths', type: 'textarea', label: 'Key Strengths & Achievements', required: true, validation: { minLength: 20, maxLength: 1000 }, placeholder: 'Describe their top achievements, skills, and qualities...' },
      { id: 'roleApplyingFor', type: 'text', label: 'Role/Program Applying For', required: false, validation: { maxLength: 200 } },
    ],
    groups: [
      { id: 'writer', title: 'Writer Info', fieldIds: ['writerName', 'writerTitle', 'writerCompany'] },
      { id: 'candidate', title: 'Candidate', fieldIds: ['candidateName', 'referenceType', 'relationship', 'roleApplyingFor'] },
      { id: 'content', title: 'Content', fieldIds: ['keyStrengths'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an expert at writing compelling reference letters. Generate sincere, specific, and persuasive reference letters that stand out.' },
      { id: 'generate', role: 'user', template: `Generate a {{referenceType}} reference letter:\n\nFrom: {{writerName}}, {{writerTitle}} at {{writerCompany}}\nFor: {{candidateName}}\nRelationship: {{relationship}}\nApplying for: {{roleApplyingFor}}\nStrengths: {{keyStrengths}}\n\nWrite a compelling 3-4 paragraph letter that: introduces the writer and their relationship to the candidate, highlights specific achievements and strengths with examples, makes a strong recommendation, and ends professionally.` },
    ],
    outputFormat: 'text',
    maxTokens: 1200,
    temperature: 0.5,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Reference-Letter-{{candidateName}}', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Reference Letter Generator — Professional Recommendation | AIFreeTools',
    descriptionTemplate: 'Generate a compelling reference letter for employees, students, or colleagues. AI-powered, multiple types available. Free PDF download.',
    primaryKeyword: 'reference letter generator',
    keywords: ['reference letter generator', 'recommendation letter generator', 'free reference letter', 'letter of recommendation template', 'employment reference letter'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['how to write a reference letter', 'reference letter vs recommendation letter', 'reference letter format'],
    relatedTools: ['resignation-letter-generator', 'job-offer-letter-generator', 'performance-review-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['linkedin', 'indeed'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const performanceReviewGenerator: ToolConfig = {
  id: 'performance-review-generator',
  slug: 'performance-review-generator',
  name: 'Free Performance Review Generator',
  shortName: 'Performance Review Generator',
  category: 'hr-recruitment',
  description: 'Generate balanced, constructive performance reviews with strengths analysis, improvement areas, and SMART goal suggestions.',
  tagline: 'Write fair, constructive performance reviews with AI.',
  icon: 'bar-chart',
  sortOrder: 22,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'employeeName', type: 'text', label: 'Employee Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'jobTitle', type: 'text', label: 'Job Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'reviewPeriod', type: 'text', label: 'Review Period', required: true, placeholder: 'e.g. Q4 2025 or Jan-Dec 2025' },
      { id: 'overallRating', type: 'select', label: 'Overall Performance Rating', required: true, options: [{ value: 'exceptional', label: 'Exceptional (5/5)' }, { value: 'exceeds', label: 'Exceeds Expectations (4/5)' }, { value: 'meets', label: 'Meets Expectations (3/5)' }, { value: 'needs_improvement', label: 'Needs Improvement (2/5)' }, { value: 'unsatisfactory', label: 'Unsatisfactory (1/5)' }] },
      { id: 'strengths', type: 'textarea', label: 'Key Strengths & Achievements', required: true, validation: { minLength: 20, maxLength: 1000 } },
      { id: 'improvements', type: 'textarea', label: 'Areas for Improvement', required: true, validation: { minLength: 10, maxLength: 1000 } },
      { id: 'goals', type: 'textarea', label: 'Goals for Next Period', required: false, validation: { maxLength: 1000 } },
      { id: 'tone', type: 'radio', label: 'Review Tone', required: true, defaultValue: 'constructive', options: [{ value: 'constructive', label: 'Constructive & Balanced' }, { value: 'positive', label: 'Positive Focus' }, { value: 'developmental', label: 'Development-Focused' }] },
    ],
    groups: [
      { id: 'details', title: 'Employee Details', fieldIds: ['employeeName', 'jobTitle', 'reviewPeriod', 'overallRating'] },
      { id: 'content', title: 'Review Content', fieldIds: ['strengths', 'improvements', 'goals', 'tone'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an HR professional and performance management expert. Generate fair, specific, and constructive performance reviews that motivate employees and align with company goals.' },
      { id: 'generate', role: 'user', template: `Generate a {{tone}} performance review:\n\nEmployee: {{employeeName}} ({{jobTitle}})\nPeriod: {{reviewPeriod}}\nRating: {{overallRating}}\nStrengths: {{strengths}}\nImprovements: {{improvements}}\nGoals: {{goals}}\n\nWrite a professional review with: opening summary with rating, achievements section (specific examples), areas for improvement (constructive, not punitive), SMART goals for next period, closing statement. Balance positive with developmental feedback. Avoid vague language.` },
    ],
    outputFormat: 'text',
    maxTokens: 1500,
    temperature: 0.4,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Performance-Review-{{employeeName}}', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Performance Review Generator — AI Employee Reviews | AIFreeTools',
    descriptionTemplate: 'Generate constructive, fair performance reviews with AI. Includes strengths, improvement areas, and SMART goals. Free PDF download.',
    primaryKeyword: 'performance review generator',
    keywords: ['performance review generator', 'employee review generator', 'performance appraisal template', 'annual review generator', 'performance evaluation tool'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['how to write a performance review', 'performance review best practices', 'smart goals for employees', 'giving constructive feedback'],
    relatedTools: ['pip-generator', 'employee-warning-letter-generator', 'job-description-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['bamboohr', 'lattice', 'culture-amp', 'leapsome'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const interviewQuestionsGenerator: ToolConfig = {
  id: 'interview-questions-generator',
  slug: 'interview-questions-generator',
  name: 'Free Interview Questions Generator',
  shortName: 'Interview Questions Generator',
  category: 'hr-recruitment',
  description: 'Generate role-specific interview questions including behavioral, technical, and situational questions with ideal answer guidelines.',
  tagline: 'Generate targeted interview questions that find the best candidates.',
  icon: 'help-circle',
  sortOrder: 23,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'jobTitle', type: 'text', label: 'Job Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'industry', type: 'select', label: 'Industry', required: false, options: [{ value: 'technology', label: 'Technology' }, { value: 'marketing', label: 'Marketing' }, { value: 'sales', label: 'Sales' }, { value: 'finance', label: 'Finance' }, { value: 'hr', label: 'HR' }, { value: 'design', label: 'Design' }, { value: 'operations', label: 'Operations' }, { value: 'legal', label: 'Legal' }, { value: 'customer_service', label: 'Customer Service' }, { value: 'other', label: 'Other' }] },
      { id: 'experienceLevel', type: 'select', label: 'Experience Level', required: true, options: [{ value: 'entry', label: 'Entry Level' }, { value: 'mid', label: 'Mid Level' }, { value: 'senior', label: 'Senior' }, { value: 'executive', label: 'Executive' }] },
      { id: 'questionTypes', type: 'multiselect', label: 'Question Types', required: true, options: [{ value: 'behavioral', label: 'Behavioral (STAR method)' }, { value: 'situational', label: 'Situational' }, { value: 'technical', label: 'Technical' }, { value: 'cultural_fit', label: 'Culture Fit' }, { value: 'leadership', label: 'Leadership' }, { value: 'motivation', label: 'Motivation & Goals' }] },
      { id: 'keySkills', type: 'textarea', label: 'Key Skills to Assess', required: true, validation: { minLength: 10, maxLength: 500 }, placeholder: 'List the top skills and qualities you need to assess...' },
      { id: 'questionCount', type: 'select', label: 'Number of Questions', required: true, defaultValue: '10', options: [{ value: '5', label: '5 Questions' }, { value: '10', label: '10 Questions' }, { value: '15', label: '15 Questions' }, { value: '20', label: '20 Questions' }] },
    ],
    groups: [
      { id: 'role', title: 'Role Details', fieldIds: ['jobTitle', 'industry', 'experienceLevel'] },
      { id: 'questions', title: 'Question Configuration', fieldIds: ['questionTypes', 'keySkills', 'questionCount'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an expert talent acquisition specialist and behavioral interviewer. Generate targeted, insightful interview questions that reveal candidate competency and culture fit.' },
      { id: 'generate', role: 'user', template: `Generate {{questionCount}} interview questions for:\n\nRole: {{jobTitle}} ({{experienceLevel}})\nIndustry: {{industry}}\nTypes: {{questionTypes}}\nAssess: {{keySkills}}\n\nFor each question:\n1. State the question clearly\n2. Note what competency it assesses\n3. Provide ideal answer indicators (what to listen for)\n\nMix question types as requested. Include follow-up probes where appropriate. Avoid illegal questions (age, religion, marital status, etc.).` },
    ],
    outputFormat: 'text',
    maxTokens: 2500,
    temperature: 0.5,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Interview-Questions-{{jobTitle}}', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Interview Questions Generator — Role-Specific AI Questions | AIFreeTools',
    descriptionTemplate: 'Generate targeted behavioral, technical, and situational interview questions for any role. AI-powered, free PDF download for hiring managers.',
    primaryKeyword: 'interview questions generator',
    keywords: ['interview questions generator', 'behavioral interview questions', 'technical interview questions', 'situational interview questions', 'hr interview questions'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['behavioral interview questions guide', 'star method interview technique', 'interview questions to avoid (illegal)', 'best interview questions for hiring managers'],
    relatedTools: ['job-description-generator', 'job-offer-letter-generator', 'performance-review-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['greenhouse', 'lever', 'workday', 'bamboohr'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const jobOfferLetterGenerator: ToolConfig = {
  id: 'job-offer-letter-generator',
  slug: 'job-offer-letter-generator',
  name: 'Free Job Offer Letter Generator',
  shortName: 'Job Offer Letter Generator',
  category: 'hr-recruitment',
  description: 'Generate professional job offer letters with compensation, benefits, start date, and conditions of employment.',
  tagline: 'Generate a professional job offer letter that wins candidates.',
  icon: 'mail',
  sortOrder: 24,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'candidateName', type: 'text', label: 'Candidate Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'jobTitle', type: 'text', label: 'Job Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'startDate', type: 'date', label: 'Proposed Start Date', required: false },
      { id: 'salary', type: 'currency', label: 'Annual Salary ($)', required: true, validation: { min: 1 } },
      { id: 'payFrequency', type: 'select', label: 'Pay Frequency', required: true, defaultValue: 'bi_weekly', options: [{ value: 'weekly', label: 'Weekly' }, { value: 'bi_weekly', label: 'Bi-Weekly' }, { value: 'semi_monthly', label: 'Semi-Monthly' }, { value: 'monthly', label: 'Monthly' }] },
      { id: 'workLocation', type: 'radio', label: 'Work Location', required: true, defaultValue: 'hybrid', options: [{ value: 'onsite', label: 'On-site' }, { value: 'remote', label: 'Remote' }, { value: 'hybrid', label: 'Hybrid' }] },
      { id: 'benefits', type: 'multiselect', label: 'Benefits Included', required: false, options: [{ value: 'health', label: 'Health Insurance' }, { value: 'dental', label: 'Dental & Vision' }, { value: '401k', label: '401(k)' }, { value: 'pto', label: 'PTO' }, { value: 'equity', label: 'Stock/Equity' }, { value: 'bonus', label: 'Performance Bonus' }, { value: 'remote_stipend', label: 'Remote Work Stipend' }, { value: 'learning', label: 'Learning & Development' }] },
      { id: 'contingencies', type: 'multiselect', label: 'Offer Contingencies', required: false, options: [{ value: 'background_check', label: 'Background Check' }, { value: 'reference_check', label: 'Reference Check' }, { value: 'drug_test', label: 'Drug Test' }, { value: 'work_authorization', label: 'Work Authorization' }] },
      { id: 'acceptanceDeadline', type: 'date', label: 'Acceptance Deadline', required: false },
    ],
    groups: [
      { id: 'offer', title: 'Offer Details', fieldIds: ['company', 'candidateName', 'jobTitle', 'startDate', 'workLocation'] },
      { id: 'compensation', title: 'Compensation', fieldIds: ['salary', 'payFrequency', 'benefits'] },
      { id: 'conditions', title: 'Conditions', fieldIds: ['contingencies', 'acceptanceDeadline'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an HR professional. Generate warm, professional job offer letters that are legally appropriate and compelling to candidates.' },
      { id: 'generate', role: 'user', template: `Generate a job offer letter:\n\nCompany: {{company}}\nCandidate: {{candidateName}}\nRole: {{jobTitle}} | {{workLocation}}\nStart: {{startDate}}\nSalary: \$\{\{salary}} ({{payFrequency}})\nBenefits: {{benefits}}\nContingencies: {{contingencies}}\nAccept By: {{acceptanceDeadline}}\n\nWrite a warm, professional offer letter that: congratulates candidate, states the position and terms clearly, lists compensation and benefits, notes any contingencies, sets acceptance deadline, expresses enthusiasm for them joining. Professional but human tone.` },
    ],
    outputFormat: 'text',
    maxTokens: 1200,
    temperature: 0.4,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Job-Offer-Letter-{{candidateName}}', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Job Offer Letter Generator — Professional Templates | AIFreeTools',
    descriptionTemplate: 'Generate a professional job offer letter with compensation, benefits, and contingencies. Free AI-powered, PDF download for HR teams.',
    primaryKeyword: 'job offer letter generator',
    keywords: ['job offer letter generator', 'employment offer letter template', 'free job offer letter', 'offer letter template', 'hr offer letter'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['how to write a job offer letter', 'job offer letter vs employment contract', 'offer letter negotiation tips'],
    relatedTools: ['job-description-generator', 'termination-letter-generator', 'employee-warning-letter-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['gusto', 'bamboohr', 'rippling'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const employeeWarningLetter: ToolConfig = {
  id: 'employee-warning-letter-generator',
  slug: 'employee-warning-letter-generator',
  name: 'Free Employee Warning Letter Generator',
  shortName: 'Warning Letter Generator',
  category: 'hr-recruitment',
  description: 'Generate professional employee warning letters with HR-compliant language, policy references, and clear expectations.',
  tagline: 'Generate a fair, compliant employee warning letter.',
  icon: 'alert-circle',
  sortOrder: 25,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'employeeName', type: 'text', label: 'Employee Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'issuerName', type: 'text', label: 'Manager/HR Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'issuerTitle', type: 'text', label: 'Manager/HR Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'warningLevel', type: 'select', label: 'Warning Level', required: true, options: [{ value: 'verbal', label: 'Verbal Warning (Documented)' }, { value: 'first', label: 'First Written Warning' }, { value: 'final', label: 'Final Written Warning' }] },
      { id: 'violationType', type: 'select', label: 'Violation Type', required: true, options: [{ value: 'attendance', label: 'Attendance/Tardiness' }, { value: 'performance', label: 'Performance Issues' }, { value: 'conduct', label: 'Misconduct/Behavior' }, { value: 'policy', label: 'Policy Violation' }, { value: 'insubordination', label: 'Insubordination' }] },
      { id: 'description', type: 'textarea', label: 'Description of Violation', required: true, validation: { minLength: 20, maxLength: 1000 } },
      { id: 'expectedBehavior', type: 'textarea', label: 'Expected Behavior / Corrective Action', required: true, validation: { minLength: 10, maxLength: 500 } },
      { id: 'improvementDeadline', type: 'date', label: 'Improvement Deadline', required: false },
    ],
    groups: [
      { id: 'parties', title: 'Parties', fieldIds: ['employeeName', 'company', 'issuerName', 'issuerTitle'] },
      { id: 'warning', title: 'Warning Details', fieldIds: ['warningLevel', 'violationType', 'description'] },
      { id: 'corrective', title: 'Corrective Action', fieldIds: ['expectedBehavior', 'improvementDeadline'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an HR attorney and employment law specialist. Generate compliant, fair, and clear employee warning letters that protect the company while respecting employee rights.' },
      { id: 'generate', role: 'user', template: `Generate an employee {{warningLevel}} warning letter:\n\nEmployee: {{employeeName}}\nCompany: {{company}}\nIssued by: {{issuerName}}, {{issuerTitle}}\nViolation: {{violationType}}\nDescription: {{description}}\nExpected: {{expectedBehavior}}\nDeadline: {{improvementDeadline}}\n\nProfessional tone. Include: date, employee info, specific violation with dates/facts, policy reference, expected improvement, timeline, consequences of non-improvement, signature line. HR-compliant language. Fair and fact-based.` },
    ],
    outputFormat: 'text',
    maxTokens: 1200,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Employee-Warning-Letter', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Employee Warning Letter Generator — HR Templates | AIFreeTools',
    descriptionTemplate: 'Generate professional employee warning letters with HR-compliant language. First, final written warnings. Free PDF download.',
    primaryKeyword: 'employee warning letter generator',
    keywords: ['employee warning letter generator', 'written warning template', 'hr warning letter', 'employee disciplinary letter', 'workplace warning letter'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['how to write an employee warning letter', 'progressive discipline guide', 'employee warning letter best practices'],
    relatedTools: ['pip-generator', 'termination-letter-generator', 'performance-review-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['bamboohr', 'rippling', 'gusto'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const pipGenerator: ToolConfig = {
  id: 'pip-generator',
  slug: 'pip-generator',
  name: 'Free PIP Generator',
  shortName: 'PIP Generator',
  category: 'hr-recruitment',
  description: 'Generate a Performance Improvement Plan (PIP) with measurable SMART goals, timelines, and support provisions.',
  tagline: 'Create a fair, actionable Performance Improvement Plan.',
  icon: 'target',
  sortOrder: 26,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'employeeName', type: 'text', label: 'Employee Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'jobTitle', type: 'text', label: 'Job Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'managerName', type: 'text', label: 'Manager Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'pipDuration', type: 'select', label: 'PIP Duration', required: true, defaultValue: '90', options: [{ value: '30', label: '30 Days' }, { value: '60', label: '60 Days' }, { value: '90', label: '90 Days' }] },
      { id: 'performanceIssues', type: 'textarea', label: 'Performance Issues', required: true, validation: { minLength: 20, maxLength: 1000 } },
      { id: 'goals', type: 'textarea', label: 'Improvement Goals', required: true, validation: { minLength: 20, maxLength: 1000 }, placeholder: 'List specific, measurable improvement goals...' },
      { id: 'support', type: 'textarea', label: 'Support & Resources Provided', required: false, validation: { maxLength: 500 }, placeholder: 'Training, coaching, tools provided...' },
      { id: 'checkInFrequency', type: 'select', label: 'Check-in Frequency', required: true, defaultValue: 'weekly', options: [{ value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'bi_weekly', label: 'Bi-Weekly' }] },
    ],
    groups: [
      { id: 'employee', title: 'Employee', fieldIds: ['employeeName', 'jobTitle', 'company', 'managerName'] },
      { id: 'plan', title: 'PIP Details', fieldIds: ['pipDuration', 'performanceIssues', 'goals', 'support', 'checkInFrequency'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an HR specialist in performance management. Generate fair, constructive Performance Improvement Plans with SMART goals that give employees a genuine opportunity to succeed.' },
      { id: 'generate', role: 'user', template: `Generate a Performance Improvement Plan (PIP):\n\nEmployee: {{employeeName}} ({{jobTitle}})\nCompany: {{company}}\nManager: {{managerName}}\nDuration: {{pipDuration}} days\nIssues: {{performanceIssues}}\nGoals: {{goals}}\nSupport: {{support}}\nCheck-ins: {{checkInFrequency}}\n\nCreate a structured PIP with: purpose statement, performance issues with specific examples, SMART improvement goals with metrics, support provided, check-in schedule, consequences of not meeting goals, success criteria, acknowledgment signature section.` },
    ],
    outputFormat: 'text',
    maxTokens: 2000,
    temperature: 0.3,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'PIP-{{employeeName}}', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free PIP Generator — Performance Improvement Plan Template | AIFreeTools',
    descriptionTemplate: 'Generate a fair Performance Improvement Plan with SMART goals and measurable outcomes. Free AI-powered PIP template. PDF download.',
    primaryKeyword: 'pip generator',
    keywords: ['pip generator', 'performance improvement plan generator', 'pip template', 'performance improvement plan template', 'employee pip maker'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['what is a pip', 'how to write a performance improvement plan', 'smart goals for employees', 'pip vs termination'],
    relatedTools: ['employee-warning-letter-generator', 'performance-review-generator', 'termination-letter-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['bamboohr', 'lattice', 'workday'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

const jobRejectionEmailGenerator: ToolConfig = {
  id: 'job-rejection-email-generator',
  slug: 'job-rejection-email-generator',
  name: 'Free Job Rejection Email Generator',
  shortName: 'Rejection Email Generator',
  category: 'hr-recruitment',
  description: 'Generate empathetic, professional job rejection emails that preserve employer brand and maintain positive candidate relationships.',
  tagline: 'Reject candidates gracefully while protecting your employer brand.',
  icon: 'x',
  sortOrder: 27,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'candidateName', type: 'text', label: 'Candidate Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'jobTitle', type: 'text', label: 'Position Applied For', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'interviewStage', type: 'select', label: 'How Far They Got', required: true, options: [{ value: 'application', label: 'Application Review' }, { value: 'phone_screen', label: 'Phone Screen' }, { value: 'first_interview', label: 'First Interview' }, { value: 'final_round', label: 'Final Round' }] },
      { id: 'tone', type: 'radio', label: 'Email Tone', required: true, defaultValue: 'warm', options: [{ value: 'warm', label: 'Warm & Personal' }, { value: 'professional', label: 'Professional & Brief' }] },
      { id: 'keepOnFile', type: 'toggle', label: 'Offer to keep them in file?', defaultValue: true },
      { id: 'feedback', type: 'toggle', label: 'Offer brief feedback? (final round only)', defaultValue: false },
    ],
    groups: [
      { id: 'details', title: 'Details', fieldIds: ['company', 'candidateName', 'jobTitle', 'interviewStage'] },
      { id: 'options', title: 'Options', fieldIds: ['tone', 'keepOnFile', 'feedback'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a talent acquisition expert and employer branding specialist. Write rejection emails that are empathetic, respectful, and protect the company\'s employer brand.' },
      { id: 'generate', role: 'user', template: `Generate a job rejection email:\n\nCompany: {{company}}\nCandidate: {{candidateName}}\nPosition: {{jobTitle}}\nStage: {{interviewStage}}\nTone: {{tone}}\nKeep on file: {{keepOnFile}}\nOffer feedback: {{feedback}}\n\nWrite a {{tone}} rejection email that: thanks them for their time, delivers the rejection clearly but kindly, {{#if keepOnFile}}invites them to future opportunities{{/if}}, {{#if feedback}}offers brief constructive feedback{{/if}}, wishes them well. Under 150 words. No vague reasons.` },
    ],
    outputFormat: 'text',
    maxTokens: 400,
    temperature: 0.5,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: HR_TEMPLATE, fileNameTemplate: 'Job-Rejection-Email', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Job Rejection Email Generator — Empathetic Templates | AIFreeTools',
    descriptionTemplate: 'Generate kind, professional job rejection emails that protect your employer brand. AI-powered, multiple tones. Free for HR teams.',
    primaryKeyword: 'job rejection email generator',
    keywords: ['job rejection email generator', 'candidate rejection email template', 'hr rejection letter', 'application rejection email', 'interview rejection email'],
    faqCount: 5,
    generateStatePages: false,
    articleTopics: ['how to reject candidates professionally', 'employer branding in hiring', 'candidate experience best practices'],
    relatedTools: ['job-offer-letter-generator', 'job-description-generator', 'interview-questions-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['greenhouse', 'lever', 'bamboohr'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'copy',
  },
};

const terminationLetterGenerator: ToolConfig = {
  id: 'termination-letter-generator',
  slug: 'termination-letter-generator',
  name: 'Free Termination Letter Generator',
  shortName: 'Termination Letter Generator',
  category: 'hr-recruitment',
  description: 'Generate legally compliant employee termination letters with proper documentation of cause, final pay, and benefits information.',
  tagline: 'Generate a compliant termination letter that protects your company.',
  icon: 'user-x',
  sortOrder: 28,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'employeeName', type: 'text', label: 'Employee Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'company', type: 'text', label: 'Company Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'jobTitle', type: 'text', label: 'Employee Job Title', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'state', type: 'select', label: 'State', required: true, options: US_STATES },
      { id: 'terminationType', type: 'select', label: 'Termination Type', required: true, options: [{ value: 'for_cause', label: 'For Cause' }, { value: 'without_cause', label: 'Without Cause (Layoff)' }, { value: 'resignation', label: 'Resignation Accepted' }, { value: 'end_of_contract', label: 'End of Contract' }] },
      { id: 'lastDay', type: 'date', label: 'Last Day of Employment', required: true },
      { id: 'reason', type: 'textarea', label: 'Reason for Termination', required: true, validation: { minLength: 10, maxLength: 500 } },
      { id: 'severance', type: 'toggle', label: 'Severance Offered?', defaultValue: false },
      { id: 'cobraNotice', type: 'toggle', label: 'Include COBRA Notice?', defaultValue: true },
    ],
    groups: [
      { id: 'employee', title: 'Employee Details', fieldIds: ['employeeName', 'company', 'jobTitle', 'state'] },
      { id: 'termination', title: 'Termination Details', fieldIds: ['terminationType', 'lastDay', 'reason'] },
      { id: 'benefits', title: 'Benefits & Severance', fieldIds: ['severance', 'cobraNotice'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an employment law attorney. Generate legally appropriate termination letters that protect the company from liability while being respectful to the employee. Follow at-will employment and state-specific requirements.' },
      { id: 'generate', role: 'user', template: `Generate a termination letter:\n\nEmployee: {{employeeName}} ({{jobTitle}})\nCompany: {{company}}\nState: {{state}}\nType: {{terminationType}}\nLast Day: {{lastDay}}\nReason: {{reason}}\nSeverance: {{severance}}\nCOBRA: {{cobraNotice}}\n\nInclude: notification of termination effective date, reason (appropriately worded for {{terminationType}}), final pay info, benefits continuation, return of company property, {{#if cobraNotice}}COBRA notice requirement for {{state}}{{/if}}, {{#if severance}}severance agreement reference{{/if}}. Professional, factual, legally appropriate.` },
    ],
    outputFormat: 'text',
    maxTokens: 1500,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: HR_TEMPLATE, docxTemplate: LEGAL_TEMPLATE, fileNameTemplate: 'Termination-Letter', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Termination Letter Generator — Legal Compliance | AIFreeTools',
    descriptionTemplate: 'Generate a legally compliant employee termination letter. Covers for-cause, layoff, COBRA notices. Free AI-powered, state-specific. PDF download.',
    primaryKeyword: 'termination letter generator',
    keywords: ['termination letter generator', 'employee termination letter', 'firing letter template', 'separation letter generator', 'termination of employment letter'],
    faqCount: 7,
    generateStatePages: true,
    articleTopics: ['how to terminate an employee legally', 'at-will employment explained', 'final pay laws by state', 'wrongful termination prevention'],
    relatedTools: ['employee-warning-letter-generator', 'pip-generator', 'job-offer-letter-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['legalzoom', 'gusto', 'rippling'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
    leadGenCTA: 'Need an employment attorney? Find one in your state.',
  },
};

export const CATEGORY_3_TOOLS: ToolConfig[] = [
  jobDescriptionGenerator,
  resignationLetterGenerator,
  referenceLetterGenerator,
  performanceReviewGenerator,
  interviewQuestionsGenerator,
  jobOfferLetterGenerator,
  employeeWarningLetter,
  pipGenerator,
  jobRejectionEmailGenerator,
  terminationLetterGenerator,
];
