import type { ToolConfig } from '@aifreetools/shared-types';
import { US_STATES, LEGAL_TEMPLATE, FINANCE_TEMPLATE } from '../constants';

export const evictionNoticeGenerator: ToolConfig = {
  id: 'eviction-notice-generator',
  slug: 'eviction-notice-generator',
  name: 'Free Eviction Notice Generator',
  shortName: 'Eviction Notice Generator',
  category: 'real-estate',
  description: 'Generate a legally compliant eviction notice for non-payment, lease violations, or end of tenancy. State-specific requirements supported.',
  tagline: 'Generate a state-compliant eviction notice in minutes.',
  icon: 'home',
  sortOrder: 11,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'landlordName', type: 'text', label: 'Landlord Name/Company', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'tenantName', type: 'text', label: 'Tenant Name(s)', required: true, validation: { minLength: 2, maxLength: 300 } },
      { id: 'propertyAddress', type: 'textarea', label: 'Property Address', required: true, validation: { minLength: 10, maxLength: 500 } },
      { id: 'state', type: 'select', label: 'Property State', required: true, options: US_STATES },
      { id: 'noticeType', type: 'select', label: 'Notice Type', required: true, options: [{ value: 'pay_or_quit', label: 'Pay or Quit (Non-Payment)' }, { value: 'cure_or_quit', label: 'Cure or Quit (Lease Violation)' }, { value: 'unconditional_quit', label: 'Unconditional Quit' }, { value: 'no_fault', label: 'No-Fault / End of Tenancy' }] },
      { id: 'amountOwed', type: 'currency', label: 'Amount Owed ($)', required: false, showWhen: { field: 'noticeType', operator: 'equals', value: 'pay_or_quit' } },
      { id: 'violationDescription', type: 'textarea', label: 'Violation Description', required: false, validation: { maxLength: 1000 }, showWhen: { field: 'noticeType', operator: 'equals', value: 'cure_or_quit' } },
      { id: 'noticePeriod', type: 'select', label: 'Notice Period', required: true, defaultValue: '3', options: [{ value: '3', label: '3 Days' }, { value: '5', label: '5 Days' }, { value: '7', label: '7 Days' }, { value: '14', label: '14 Days' }, { value: '30', label: '30 Days' }, { value: '60', label: '60 Days' }] },
    ],
    groups: [
      { id: 'parties', title: 'Parties & Property', fieldIds: ['landlordName', 'tenantName', 'propertyAddress', 'state'] },
      { id: 'notice', title: 'Notice Details', fieldIds: ['noticeType', 'amountOwed', 'violationDescription', 'noticePeriod'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a real estate law attorney specializing in landlord-tenant law. Generate legally compliant eviction notices that follow state-specific procedural requirements.' },
      { id: 'generate', role: 'user', template: `Generate an Eviction Notice:\n\nLandlord: {{landlordName}}\nTenant: {{tenantName}}\nProperty: {{propertyAddress}}\nState: {{state}}\nNotice Type: {{noticeType}}\nAmount Owed: \$\{\{amountOwed}}\nViolation: {{violationDescription}}\nNotice Period: {{noticePeriod}} days\n\nMust comply with {{state}} landlord-tenant law. Include correct notice period, proper service instructions, and tenant's rights. Note any {{state}}-specific requirements.` },
    ],
    outputFormat: 'text',
    maxTokens: 2000,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: LEGAL_TEMPLATE, docxTemplate: LEGAL_TEMPLATE, fileNameTemplate: 'Eviction-Notice', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Eviction Notice Generator — State-Compliant | AIFreeTools',
    descriptionTemplate: 'Generate a state-compliant eviction notice for non-payment or lease violations. Free AI-powered, all 50 states. PDF download.',
    primaryKeyword: 'free eviction notice generator',
    keywords: ['eviction notice generator', 'free eviction notice', 'pay or quit notice', 'eviction letter template', 'notice to vacate generator'],
    faqCount: 7,
    generateStatePages: true,
    articleTopics: ['eviction process by state', 'how to evict a tenant', 'pay or quit notice explained', 'tenant eviction rights'],
    relatedTools: ['lease-agreement-generator', 'demand-letter-generator', 'rental-application-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['stessa', 'buildium', 'rentec-direct'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

export const realEstateOfferLetter: ToolConfig = {
  id: 'real-estate-offer-letter-generator',
  slug: 'real-estate-offer-letter-generator',
  name: 'Real Estate Offer Letter Generator',
  shortName: 'Offer Letter Generator',
  category: 'real-estate',
  description: 'Generate a compelling real estate offer letter with negotiation wording, contingency clauses, and financing terms.',
  tagline: 'Write a compelling real estate offer that gets accepted.',
  icon: 'key',
  sortOrder: 12,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'buyerName', type: 'text', label: 'Buyer Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'sellerName', type: 'text', label: 'Seller Name', required: false, validation: { maxLength: 200 } },
      { id: 'propertyAddress', type: 'textarea', label: 'Property Address', required: true, validation: { minLength: 10, maxLength: 500 } },
      { id: 'state', type: 'select', label: 'Property State', required: true, options: US_STATES },
      { id: 'offerPrice', type: 'currency', label: 'Offer Price ($)', required: true, validation: { min: 1 } },
      { id: 'downPayment', type: 'currency', label: 'Down Payment ($)', required: true, validation: { min: 0 } },
      { id: 'financingType', type: 'select', label: 'Financing Type', required: true, options: [{ value: 'conventional', label: 'Conventional Loan' }, { value: 'fha', label: 'FHA Loan' }, { value: 'va', label: 'VA Loan' }, { value: 'cash', label: 'Cash' }, { value: 'hard_money', label: 'Hard Money' }] },
      { id: 'closingDate', type: 'date', label: 'Desired Closing Date', required: false },
      { id: 'contingencies', type: 'multiselect', label: 'Contingencies', required: false, options: [{ value: 'inspection', label: 'Home Inspection' }, { value: 'financing', label: 'Financing' }, { value: 'appraisal', label: 'Appraisal' }, { value: 'sale_of_home', label: 'Sale of Current Home' }] },
      { id: 'earnestMoney', type: 'currency', label: 'Earnest Money Deposit ($)', required: false, validation: { min: 0 } },
      { id: 'tone', type: 'radio', label: 'Letter Tone', required: true, defaultValue: 'professional', options: [{ value: 'professional', label: 'Professional' }, { value: 'personal', label: 'Personal & Heartfelt' }, { value: 'competitive', label: 'Competitive (Strong Offer)' }] },
    ],
    groups: [
      { id: 'parties', title: 'Parties & Property', fieldIds: ['buyerName', 'sellerName', 'propertyAddress', 'state'] },
      { id: 'financials', title: 'Offer Details', fieldIds: ['offerPrice', 'downPayment', 'earnestMoney', 'financingType', 'closingDate'] },
      { id: 'terms', title: 'Terms', fieldIds: ['contingencies', 'tone'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a real estate attorney and negotiation expert. Generate compelling offer letters that are professionally written and improve the buyer\'s chances of acceptance.' },
      { id: 'generate', role: 'user', template: `Generate a Real Estate Offer Letter:\n\nBuyer: {{buyerName}}\nSeller: {{sellerName}}\nProperty: {{propertyAddress}}\nState: {{state}}\nOffer: \$\{\{offerPrice}}\nDown Payment: \$\{\{downPayment}}\nFinancing: {{financingType}}\nClosing: {{closingDate}}\nContingencies: {{contingencies}}\nEarnest Money: \$\{\{earnestMoney}}\nTone: {{tone}}\n\nWrite a {{tone}} offer letter that clearly states the offer terms, demonstrates the buyer's seriousness, and addresses any competitive elements.` },
    ],
    outputFormat: 'text',
    maxTokens: 2000,
    temperature: 0.4,
  },
  exportConfig: { pdfTemplate: LEGAL_TEMPLATE, docxTemplate: LEGAL_TEMPLATE, fileNameTemplate: 'Real-Estate-Offer-Letter', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Real Estate Offer Letter Generator — Win the Bid | AIFreeTools',
    descriptionTemplate: 'Generate a compelling real estate offer letter with AI. Cover financing, contingencies, and personal appeal. Free PDF download.',
    primaryKeyword: 'real estate offer letter generator',
    keywords: ['real estate offer letter', 'home offer letter generator', 'house offer letter template', 'real estate letter of intent'],
    faqCount: 6,
    generateStatePages: true,
    articleTopics: ['how to write a real estate offer letter', 'tips for winning a home bid', 'real estate offer contingencies'],
    relatedTools: ['lease-agreement-generator', 'real-estate-roi-calculator', 'mortgage-affordability-calculator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['realtor-com', 'zillow', 'redfin'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

export const rentalApplicationGenerator: ToolConfig = {
  id: 'rental-application-generator',
  slug: 'rental-application-generator',
  name: 'Free Rental Application Generator',
  shortName: 'Rental Application Generator',
  category: 'real-estate',
  description: 'Generate a comprehensive rental application form with tenant screening fields, employment verification, and reference sections.',
  tagline: 'Create a professional rental application form for your property.',
  icon: 'clipboard',
  sortOrder: 13,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'landlordName', type: 'text', label: 'Landlord/Property Manager Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'propertyAddress', type: 'textarea', label: 'Rental Property Address', required: true, validation: { minLength: 10, maxLength: 500 } },
      { id: 'state', type: 'select', label: 'Property State', required: true, options: US_STATES },
      { id: 'monthlyRent', type: 'currency', label: 'Monthly Rent ($)', required: true, validation: { min: 1 } },
      { id: 'creditCheckConsent', type: 'toggle', label: 'Include Credit Check Consent?', defaultValue: true },
      { id: 'backgroundCheckConsent', type: 'toggle', label: 'Include Background Check Consent?', defaultValue: true },
      { id: 'applicationFee', type: 'currency', label: 'Application Fee ($)', required: false, validation: { min: 0, max: 500 } },
      { id: 'petPolicy', type: 'radio', label: 'Pet Policy', defaultValue: 'no_pets', options: [{ value: 'no_pets', label: 'No Pets' }, { value: 'pets_allowed', label: 'Pets Allowed (with deposit)' }, { value: 'case_by_case', label: 'Case-by-Case' }] },
    ],
    groups: [
      { id: 'property', title: 'Property Details', fieldIds: ['landlordName', 'propertyAddress', 'state', 'monthlyRent', 'applicationFee'] },
      { id: 'screening', title: 'Screening', fieldIds: ['creditCheckConsent', 'backgroundCheckConsent', 'petPolicy'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a property management expert. Generate comprehensive rental applications that comply with fair housing laws and collect all necessary screening information.' },
      { id: 'generate', role: 'user', template: `Generate a Rental Application for:\n\nLandlord: {{landlordName}}\nProperty: {{propertyAddress}}\nState: {{state}}\nRent: \$\{\{monthlyRent}}\nApp Fee: \$\{\{applicationFee}}\nCredit Check: {{creditCheckConsent}}\nBackground Check: {{backgroundCheckConsent}}\nPets: {{petPolicy}}\n\nCreate a complete rental application form with sections: Personal Info, Rental History, Employment, Income, References, Consent to Credit/Background Check (if applicable). Must comply with {{state}} fair housing laws.` },
    ],
    outputFormat: 'text',
    maxTokens: 3000,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: LEGAL_TEMPLATE, docxTemplate: LEGAL_TEMPLATE, fileNameTemplate: 'Rental-Application', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Rental Application Generator — Tenant Screening Form | AIFreeTools',
    descriptionTemplate: 'Generate a complete rental application form with tenant screening, credit check consent, and employment verification. Free PDF download.',
    primaryKeyword: 'rental application generator',
    keywords: ['rental application generator', 'free rental application', 'tenant application form', 'rental screening form', 'landlord rental application'],
    faqCount: 6,
    generateStatePages: true,
    articleTopics: ['how to screen tenants', 'rental application requirements by state', 'fair housing laws for landlords'],
    relatedTools: ['lease-agreement-generator', 'eviction-notice-generator', 'property-management-agreement-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['avail', 'turbotenant', 'cozy', 'rentspree'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

export const realEstateROICalculator: ToolConfig = {
  id: 'real-estate-roi-calculator',
  slug: 'real-estate-roi-calculator',
  name: 'Real Estate ROI Calculator',
  shortName: 'ROI Calculator',
  category: 'real-estate',
  description: 'Calculate your real estate investment ROI, cap rate, cash-on-cash return, and get AI-powered investment insights.',
  tagline: 'Calculate your real estate ROI and get AI investment insights.',
  icon: 'trending-up',
  sortOrder: 14,
  isFeatured: true,
  formSchema: {
    fields: [
      { id: 'purchasePrice', type: 'currency', label: 'Purchase Price ($)', required: true, validation: { min: 1 } },
      { id: 'downPayment', type: 'currency', label: 'Down Payment ($)', required: true, validation: { min: 0 } },
      { id: 'closingCosts', type: 'currency', label: 'Closing Costs ($)', required: false, validation: { min: 0 } },
      { id: 'rehabCosts', type: 'currency', label: 'Renovation/Rehab Costs ($)', required: false, validation: { min: 0 } },
      { id: 'monthlyRent', type: 'currency', label: 'Monthly Rent ($)', required: true, validation: { min: 1 } },
      { id: 'propertyTaxMonthly', type: 'currency', label: 'Property Tax ($/month)', required: true, validation: { min: 0 } },
      { id: 'insuranceMonthly', type: 'currency', label: 'Insurance ($/month)', required: true, validation: { min: 0 } },
      { id: 'maintenanceMonthly', type: 'currency', label: 'Maintenance ($/month)', required: false, validation: { min: 0 } },
      { id: 'propertyManagement', type: 'percentage', label: 'Property Management (%)', required: false, validation: { min: 0, max: 20 } },
      { id: 'vacancyRate', type: 'percentage', label: 'Expected Vacancy Rate (%)', required: false, defaultValue: '5', validation: { min: 0, max: 30 } },
      { id: 'mortgageRate', type: 'percentage', label: 'Mortgage Interest Rate (%)', required: false, validation: { min: 0, max: 20 } },
      { id: 'mortgageTerm', type: 'select', label: 'Mortgage Term', required: false, defaultValue: '30', options: [{ value: '15', label: '15 Years' }, { value: '20', label: '20 Years' }, { value: '30', label: '30 Years' }] },
      { id: 'appreciationRate', type: 'percentage', label: 'Annual Appreciation Rate (%)', required: false, defaultValue: '3', validation: { min: 0, max: 20 } },
      { id: 'state', type: 'select', label: 'Property State', required: false, options: US_STATES },
    ],
    groups: [
      { id: 'purchase', title: 'Purchase Details', fieldIds: ['purchasePrice', 'downPayment', 'closingCosts', 'rehabCosts'] },
      { id: 'income', title: 'Rental Income', fieldIds: ['monthlyRent', 'vacancyRate'] },
      { id: 'expenses', title: 'Monthly Expenses', fieldIds: ['propertyTaxMonthly', 'insuranceMonthly', 'maintenanceMonthly', 'propertyManagement'] },
      { id: 'financing', title: 'Financing', fieldIds: ['mortgageRate', 'mortgageTerm', 'appreciationRate', 'state'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a real estate investment analyst. Analyze investment property data and provide comprehensive ROI metrics with actionable insights. Always show your calculations.' },
      { id: 'generate', role: 'user', template: `Analyze this real estate investment:\n\nPurchase: \$\{\{purchasePrice}}\nDown Payment: \$\{\{downPayment}}\nClosing: \$\{\{closingCosts}}\nRehab: \$\{\{rehabCosts}}\nMonthly Rent: \$\{\{monthlyRent}}\nVacancy: {{vacancyRate}}%\nTax: \$\{\{propertyTaxMonthly}}/mo\nInsurance: \$\{\{insuranceMonthly}}/mo\nMaintenance: \$\{\{maintenanceMonthly}}/mo\nPM: {{propertyManagement}}%\nMortgage: {{mortgageRate}}% / {{mortgageTerm}}yr\nAppreciation: {{appreciationRate}}%/yr\nState: {{state}}\n\nCalculate and provide:\n1. Cap Rate\n2. Cash-on-Cash Return\n3. Gross Rent Multiplier\n4. Monthly Cash Flow\n5. Annual Cash Flow\n6. 5-Year and 10-Year ROI projection\n7. Break-even analysis\n8. Investment rating (Strong/Moderate/Weak) with reasoning\n9. Key risks and considerations\n10. Recommendations\n\nFormat clearly with sections and highlight the most important metrics.` },
    ],
    outputFormat: 'text',
    maxTokens: 2000,
    temperature: 0.3,
  },
  exportConfig: { pdfTemplate: FINANCE_TEMPLATE, docxTemplate: FINANCE_TEMPLATE, fileNameTemplate: 'Real-Estate-ROI-Analysis', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Real Estate ROI Calculator — Free AI Investment Analysis | AIFreeTools',
    descriptionTemplate: 'Calculate real estate ROI, cap rate, cash flow, and get AI investment insights. Free tool for rental property investors.',
    primaryKeyword: 'real estate roi calculator',
    keywords: ['real estate roi calculator', 'rental property roi', 'cap rate calculator', 'cash-on-cash return calculator', 'real estate investment calculator'],
    faqCount: 7,
    generateStatePages: true,
    articleTopics: ['how to calculate real estate roi', 'cap rate vs cash-on-cash return', 'best states for rental property investment', 'rental property analysis'],
    relatedTools: ['mortgage-affordability-calculator', 'rent-vs-buy-calculator', 'budget-planner'],
    searchIntent: 'informational',
  },
  monetizationConfig: {
    affiliatePartners: ['stessa', 'fundrise', 'roofstock', 'realtor-com'],
    adPlacements: ['header', 'post-result', 'sidebar', 'in-content'],
    upsellTrigger: 'export',
  },
};

export const propertyListingGenerator: ToolConfig = {
  id: 'property-listing-description-generator',
  slug: 'property-listing-description-generator',
  name: 'Property Listing Description Generator',
  shortName: 'Listing Description Generator',
  category: 'real-estate',
  description: 'Generate compelling, SEO-optimized property listing descriptions that attract buyers and renters using AI.',
  tagline: 'Write a listing description that sells your property faster.',
  icon: 'home',
  sortOrder: 15,
  isFeatured: true,
  formSchema: {
    fields: [
      { id: 'listingType', type: 'radio', label: 'Listing Type', required: true, defaultValue: 'sale', options: [{ value: 'sale', label: 'For Sale' }, { value: 'rent', label: 'For Rent' }, { value: 'vacation', label: 'Vacation Rental' }] },
      { id: 'propertyType', type: 'select', label: 'Property Type', required: true, options: [{ value: 'single_family', label: 'Single Family Home' }, { value: 'condo', label: 'Condo/Apartment' }, { value: 'townhouse', label: 'Townhouse' }, { value: 'multi_family', label: 'Multi-Family' }, { value: 'land', label: 'Land' }, { value: 'commercial', label: 'Commercial' }] },
      { id: 'bedrooms', type: 'select', label: 'Bedrooms', required: true, options: [{ value: '0', label: 'Studio' }, { value: '1', label: '1 Bed' }, { value: '2', label: '2 Beds' }, { value: '3', label: '3 Beds' }, { value: '4', label: '4 Beds' }, { value: '5+', label: '5+ Beds' }] },
      { id: 'bathrooms', type: 'select', label: 'Bathrooms', required: true, options: [{ value: '1', label: '1 Bath' }, { value: '1.5', label: '1.5 Baths' }, { value: '2', label: '2 Baths' }, { value: '2.5', label: '2.5 Baths' }, { value: '3+', label: '3+ Baths' }] },
      { id: 'squareFootage', type: 'number', label: 'Square Footage', required: false, validation: { min: 100, max: 50000 } },
      { id: 'location', type: 'text', label: 'City/Neighborhood', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'state', type: 'select', label: 'State', required: true, options: US_STATES },
      { id: 'price', type: 'currency', label: 'Price/Rent ($)', required: false },
      { id: 'keyFeatures', type: 'textarea', label: 'Key Features & Highlights', required: true, placeholder: 'e.g. Updated kitchen, hardwood floors, large backyard, near good schools...', validation: { minLength: 20, maxLength: 1000 } },
      { id: 'tone', type: 'select', label: 'Listing Tone', required: true, defaultValue: 'professional', options: [{ value: 'professional', label: 'Professional' }, { value: 'luxury', label: 'Luxury' }, { value: 'warm_inviting', label: 'Warm & Inviting' }, { value: 'investment', label: 'Investment-Focused' }] },
      { id: 'wordCount', type: 'select', label: 'Description Length', required: true, defaultValue: '200', options: [{ value: '150', label: 'Short (150 words)' }, { value: '200', label: 'Standard (200 words)' }, { value: '300', label: 'Detailed (300 words)' }, { value: '500', label: 'Comprehensive (500 words)' }] },
    ],
    groups: [
      { id: 'property', title: 'Property Details', fieldIds: ['listingType', 'propertyType', 'bedrooms', 'bathrooms', 'squareFootage', 'price'] },
      { id: 'location', title: 'Location', fieldIds: ['location', 'state'] },
      { id: 'content', title: 'Content', fieldIds: ['keyFeatures', 'tone', 'wordCount'] },
    ],
  },
  promptConfig: {
    version: '1.1.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are an expert real estate copywriter. Generate compelling property listing descriptions that highlight key features, create emotional appeal, and drive inquiries. Match the requested tone precisely.' },
      { id: 'generate', role: 'user', template: `Write a {{tone}} property listing description (~{{wordCount}} words):\n\nType: {{bedrooms}} bed / {{bathrooms}} bath {{propertyType}} {{listingType}}\nLocation: {{location}}, {{state}}\nSize: {{squareFootage}} sq ft\nPrice: \$\{\{price}}\nHighlights: {{keyFeatures}}\n\nCreate an engaging {{tone}} description that sells the property's best features, creates a picture in the reader's mind, and ends with a compelling call to action. Optimize for real estate search terms.` },
    ],
    outputFormat: 'text',
    maxTokens: 1000,
    temperature: 0.6,
  },
  exportConfig: { pdfTemplate: LEGAL_TEMPLATE, docxTemplate: LEGAL_TEMPLATE, fileNameTemplate: 'Property-Listing-Description', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Property Listing Description Generator — AI Real Estate Copy | AIFreeTools',
    descriptionTemplate: 'Generate compelling property listing descriptions with AI. Luxury, standard, or investment tone. Free for realtors and landlords.',
    primaryKeyword: 'property listing description generator',
    keywords: ['property listing description generator', 'real estate listing generator', 'mls description generator', 'home listing description', 'realtor copywriting'],
    faqCount: 6,
    generateStatePages: false,
    articleTopics: ['how to write property listing descriptions', 'real estate copywriting tips', 'luxury real estate marketing language'],
    relatedTools: ['real-estate-offer-letter-generator', 'property-management-agreement-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['zillow', 'realtor-com', 'redfin'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'copy',
  },
};

export const propertyManagementAgreement: ToolConfig = {
  id: 'property-management-agreement-generator',
  slug: 'property-management-agreement-generator',
  name: 'Property Management Agreement Generator',
  shortName: 'PM Agreement Generator',
  category: 'real-estate',
  description: 'Generate a professional Property Management Agreement defining management fees, responsibilities, maintenance authority, and termination terms.',
  tagline: 'Create a clear property management agreement for free.',
  icon: 'settings',
  sortOrder: 16,
  isFeatured: false,
  formSchema: {
    fields: [
      { id: 'ownerName', type: 'text', label: 'Property Owner Name', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'managerName', type: 'text', label: 'Property Manager/Company', required: true, validation: { minLength: 2, maxLength: 200 } },
      { id: 'propertyAddress', type: 'textarea', label: 'Property Address', required: true, validation: { minLength: 10, maxLength: 500 } },
      { id: 'state', type: 'select', label: 'Property State', required: true, options: US_STATES },
      { id: 'managementFee', type: 'percentage', label: 'Management Fee (% of rent)', required: true, validation: { min: 1, max: 30 } },
      { id: 'leaseUpFee', type: 'percentage', label: 'Lease-Up Fee (% of first month)', required: false, validation: { min: 0, max: 100 } },
      { id: 'maintenanceLimit', type: 'currency', label: 'Maintenance Approval Limit ($)', required: true, defaultValue: '500', validation: { min: 0 } },
      { id: 'contractTerm', type: 'select', label: 'Contract Term', required: true, defaultValue: '12', options: [{ value: '6', label: '6 Months' }, { value: '12', label: '1 Year' }, { value: '24', label: '2 Years' }] },
    ],
    groups: [
      { id: 'parties', title: 'Parties & Property', fieldIds: ['ownerName', 'managerName', 'propertyAddress', 'state'] },
      { id: 'fees', title: 'Fees & Authority', fieldIds: ['managementFee', 'leaseUpFee', 'maintenanceLimit', 'contractTerm'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a real estate attorney specializing in property management law. Generate comprehensive property management agreements.' },
      { id: 'generate', role: 'user', template: `Generate a Property Management Agreement:\n\nOwner: {{ownerName}}\nManager: {{managerName}}\nProperty: {{propertyAddress}}\nState: {{state}}\nManagement Fee: {{managementFee}}%\nLease-Up Fee: {{leaseUpFee}}%\nMaintenance Limit: \$\{\{maintenanceLimit}}\nTerm: {{contractTerm}} months\n\nInclude: scope of management, fees, owner's responsibilities, manager's authority, maintenance procedures, tenant relations, accounting, termination, governing law.` },
    ],
    outputFormat: 'text',
    maxTokens: 3500,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: LEGAL_TEMPLATE, docxTemplate: LEGAL_TEMPLATE, fileNameTemplate: 'Property-Management-Agreement', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Property Management Agreement Generator | AIFreeTools',
    descriptionTemplate: 'Generate a professional property management agreement defining fees, duties, and authority. Free AI-powered, all states. PDF download.',
    primaryKeyword: 'property management agreement generator',
    keywords: ['property management agreement', 'property management contract template', 'landlord property manager agreement'],
    faqCount: 6,
    generateStatePages: true,
    articleTopics: ['property management fees explained', 'hiring a property manager', 'property management agreement essentials'],
    relatedTools: ['lease-agreement-generator', 'eviction-notice-generator'],
    searchIntent: 'transactional',
  },
  monetizationConfig: {
    affiliatePartners: ['buildium', 'appfolio', 'propertyware'],
    adPlacements: ['header', 'post-result', 'sidebar'],
    upsellTrigger: 'export',
  },
};

export const mortgageAffordabilityCalculator: ToolConfig = {
  id: 'mortgage-affordability-calculator',
  slug: 'mortgage-affordability-calculator',
  name: 'Mortgage Affordability Calculator',
  shortName: 'Mortgage Calculator',
  category: 'real-estate',
  description: 'Calculate how much house you can afford based on income, debts, and down payment. Get AI-powered budgeting recommendations.',
  tagline: 'Find out exactly how much home you can afford.',
  icon: 'calculator',
  sortOrder: 17,
  isFeatured: true,
  formSchema: {
    fields: [
      { id: 'annualIncome', type: 'currency', label: 'Annual Gross Income ($)', required: true, validation: { min: 1 } },
      { id: 'coApplicantIncome', type: 'currency', label: 'Co-Applicant Annual Income ($)', required: false, validation: { min: 0 } },
      { id: 'monthlyDebts', type: 'currency', label: 'Monthly Debt Payments ($)', required: true, validation: { min: 0 }, placeholder: 'Car payments, student loans, credit cards...' },
      { id: 'downPayment', type: 'currency', label: 'Available Down Payment ($)', required: true, validation: { min: 0 } },
      { id: 'interestRate', type: 'percentage', label: 'Current Interest Rate (%)', required: true, validation: { min: 1, max: 20 } },
      { id: 'loanTerm', type: 'select', label: 'Loan Term', required: true, defaultValue: '30', options: [{ value: '15', label: '15 Years' }, { value: '20', label: '20 Years' }, { value: '30', label: '30 Years' }] },
      { id: 'creditScore', type: 'select', label: 'Credit Score Range', required: true, options: [{ value: 'excellent', label: 'Excellent (750+)' }, { value: 'very_good', label: 'Very Good (700-749)' }, { value: 'good', label: 'Good (650-699)' }, { value: 'fair', label: 'Fair (600-649)' }] },
      { id: 'state', type: 'select', label: 'Target State', required: false, options: US_STATES },
      { id: 'propertyTaxRate', type: 'percentage', label: 'Est. Property Tax Rate (%/yr)', required: false, defaultValue: '1.2', validation: { min: 0, max: 5 } },
    ],
    groups: [
      { id: 'income', title: 'Income', fieldIds: ['annualIncome', 'coApplicantIncome', 'monthlyDebts'] },
      { id: 'loan', title: 'Loan Details', fieldIds: ['downPayment', 'interestRate', 'loanTerm', 'creditScore'] },
      { id: 'location', title: 'Location', fieldIds: ['state', 'propertyTaxRate'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a mortgage advisor and financial planner. Calculate mortgage affordability with precision and provide practical, actionable advice.' },
      { id: 'generate', role: 'user', template: `Calculate mortgage affordability:\n\nIncome: \$\{\{annualIncome}} + \$\{\{coApplicantIncome}} (co-applicant)\nMonthly Debts: \$\{\{monthlyDebts}}\nDown Payment: \$\{\{downPayment}}\nRate: {{interestRate}}% / {{loanTerm}} years\nCredit: {{creditScore}}\nState: {{state}}\nProperty Tax: {{propertyTaxRate}}%/yr\n\nCalculate and provide:\n1. Maximum home price (28% and 36% DTI rules)\n2. Maximum loan amount\n3. Estimated monthly payment breakdown (P&I, taxes, insurance, PMI)\n4. Required income for $[common price points in their area]\n5. Down payment breakdown and PMI implications\n6. Recommendations to increase buying power\n7. Overall assessment and next steps` },
    ],
    outputFormat: 'text',
    maxTokens: 1500,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: FINANCE_TEMPLATE, docxTemplate: FINANCE_TEMPLATE, fileNameTemplate: 'Mortgage-Affordability-Analysis', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Mortgage Affordability Calculator — How Much House Can I Afford? | AIFreeTools',
    descriptionTemplate: 'Calculate exactly how much home you can afford based on your income and debts. Free AI-powered mortgage calculator with personalized recommendations.',
    primaryKeyword: 'mortgage affordability calculator',
    keywords: ['mortgage affordability calculator', 'how much house can i afford', 'home affordability calculator', 'mortgage calculator', 'home loan calculator'],
    faqCount: 8,
    generateStatePages: true,
    articleTopics: ['how much house can you afford', 'mortgage qualification requirements', 'first time homebuyer guide', 'improving your mortgage affordability'],
    relatedTools: ['real-estate-roi-calculator', 'rent-vs-buy-calculator', 'debt-payoff-calculator'],
    searchIntent: 'informational',
  },
  monetizationConfig: {
    affiliatePartners: ['quicken-loans', 'better-mortgage', 'zillow-home-loans', 'loan-depot'],
    adPlacements: ['header', 'post-result', 'sidebar', 'in-content'],
    upsellTrigger: 'export',
    leadGenCTA: 'Get pre-approved in minutes. Compare mortgage rates from top lenders.',
  },
};

export const rentVsBuyCalculator: ToolConfig = {
  id: 'rent-vs-buy-calculator',
  slug: 'rent-vs-buy-calculator',
  name: 'Rent vs Buy Calculator',
  shortName: 'Rent vs Buy Calculator',
  category: 'real-estate',
  description: 'Compare renting vs buying over time with AI-powered financial analysis. Find out which option makes more financial sense for your situation.',
  tagline: 'Is it better to rent or buy? Get a data-driven answer.',
  icon: 'git-compare',
  sortOrder: 18,
  isFeatured: true,
  formSchema: {
    fields: [
      { id: 'homePrice', type: 'currency', label: 'Home Purchase Price ($)', required: true, validation: { min: 1 } },
      { id: 'downPayment', type: 'percentage', label: 'Down Payment (%)', required: true, defaultValue: '20', validation: { min: 3, max: 100 } },
      { id: 'mortgageRate', type: 'percentage', label: 'Mortgage Rate (%)', required: true, validation: { min: 1, max: 20 } },
      { id: 'monthlyRent', type: 'currency', label: 'Monthly Rent Alternative ($)', required: true, validation: { min: 1 } },
      { id: 'rentIncreaseRate', type: 'percentage', label: 'Annual Rent Increase (%)', required: false, defaultValue: '3', validation: { min: 0, max: 15 } },
      { id: 'homeAppreciation', type: 'percentage', label: 'Home Appreciation Rate (%/yr)', required: false, defaultValue: '3', validation: { min: 0, max: 15 } },
      { id: 'yearsToStay', type: 'select', label: 'How Long Will You Stay?', required: true, options: [{ value: '3', label: '3 years' }, { value: '5', label: '5 years' }, { value: '7', label: '7 years' }, { value: '10', label: '10 years' }, { value: '15', label: '15+ years' }] },
      { id: 'propertyTaxRate', type: 'percentage', label: 'Property Tax Rate (%/yr)', required: false, defaultValue: '1.2' },
      { id: 'state', type: 'select', label: 'State', required: false, options: US_STATES },
    ],
    groups: [
      { id: 'buy', title: 'Buy Scenario', fieldIds: ['homePrice', 'downPayment', 'mortgageRate', 'homeAppreciation', 'propertyTaxRate'] },
      { id: 'rent', title: 'Rent Scenario', fieldIds: ['monthlyRent', 'rentIncreaseRate'] },
      { id: 'timeline', title: 'Timeline', fieldIds: ['yearsToStay', 'state'] },
    ],
  },
  promptConfig: {
    version: '1.0.0',
    steps: [
      { id: 'system', role: 'system', template: 'You are a financial advisor specializing in real estate. Provide objective rent vs buy analysis with precise calculations and clear recommendations.' },
      { id: 'generate', role: 'user', template: `Analyze Rent vs Buy decision:\n\nHome: \$\{\{homePrice}} | {{downPayment}}% down | {{mortgageRate}}% rate\nRent: \$\{\{monthlyRent}}/mo | {{rentIncreaseRate}}% annual increase\nAppreciation: {{homeAppreciation}}%/yr\nProperty Tax: {{propertyTaxRate}}%/yr\nTimeframe: {{yearsToStay}} years\nState: {{state}}\n\nProvide:\n1. Break-even point (when buying becomes cheaper)\n2. Total cost to buy vs rent over {{yearsToStay}} years\n3. Monthly buy vs rent cost comparison\n4. Net worth impact of each scenario\n5. Clear recommendation based on the numbers\n6. Factors that could change the analysis\n7. What to do next` },
    ],
    outputFormat: 'text',
    maxTokens: 1500,
    temperature: 0.2,
  },
  exportConfig: { pdfTemplate: FINANCE_TEMPLATE, docxTemplate: FINANCE_TEMPLATE, fileNameTemplate: 'Rent-vs-Buy-Analysis', pageSize: 'letter' },
  seoConfig: {
    titleTemplate: 'Free Rent vs Buy Calculator — Make the Right Financial Decision | AIFreeTools',
    descriptionTemplate: 'Compare renting vs buying with our free AI calculator. Get a personalized break-even analysis and recommendation based on your situation.',
    primaryKeyword: 'rent vs buy calculator',
    keywords: ['rent vs buy calculator', 'should i rent or buy', 'renting vs buying comparison', 'rent or buy decision tool', 'home buying break-even calculator'],
    faqCount: 7,
    generateStatePages: true,
    articleTopics: ['rent vs buy pros and cons', 'when renting beats buying', 'real estate market outlook', 'first time homebuyer tips'],
    relatedTools: ['mortgage-affordability-calculator', 'real-estate-roi-calculator', 'budget-planner'],
    searchIntent: 'informational',
  },
  monetizationConfig: {
    affiliatePartners: ['better-mortgage', 'zillow', 'apartment-list'],
    adPlacements: ['header', 'post-result', 'sidebar', 'in-content'],
    upsellTrigger: 'export',
  },
};

export const CATEGORY_2_TOOLS: ToolConfig[] = [
  evictionNoticeGenerator,
  realEstateOfferLetter,
  rentalApplicationGenerator,
  realEstateROICalculator,
  propertyListingGenerator,
  propertyManagementAgreement,
  mortgageAffordabilityCalculator,
  rentVsBuyCalculator,
];
